version: "3"
services:
  backend_01:
    image: node:16
    logging:
      options:
        max-size: "10k"
        max-file: "3"
    volumes:
      - ../backend/:/usr/local/app/backend
      - ./scripts/docker-entrypoint.sh:/docker-entrypoint.sh
    working_dir: /usr/local/app/backend
    env_file: 
      - ../.env
    ports:
     - 3000:3000
    command: /docker-entrypoint.sh